# Generated by Django 2.0 on 2019-05-29 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('endereco', models.CharField(max_length=200)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Post', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Cadastro', verbose_name='Paciente')),
            ],
        ),
    ]
