# Generated by Django 2.0 on 2019-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
