# Generated by Django 2.0 on 2019-06-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190610_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='venda',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Post', verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cadastro', verbose_name='Paciente'),
        ),
    ]
